let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
mix.setPublicPath('storage/app')
// .js('resources/js/nhap-lieu-du-lieu-nam-hoc-cu.js', 'public/js/nhap-lieu-du-lieu-nam-hoc-cu.js')
.js('resources/js/tra-cuu-diem-danh', 'public/js/tra-cuu-diem-danh.js')
// .js('resources/js/tong-hop-tuyen-sinh.js', 'public/js/tong-hop-tuyen-sinh.js')
// .js('resources/js/index.js', 'public/js/index.js')
// .js('resources/js/view-excel.js', 'public/js')
// .js('resources/js/bao-cao-tieu-chi-v2.js', 'public/js/bao-cao-tieu-chi-v2.js')
// .js('resources/js/tra-cuu-hoc-sinh-tt-26.js', 'public/js/tra-cuu-hoc-sinh-tt-26.js')
// .js('resources/js/chot-du-lieu-bao-cao.js', 'public/js/chot-du-lieu-bao-cao.js')
// .js('resources/js/chot-du-lieu-bao-cao-cap-so.js', 'public/js/chot-du-lieu-bao-cao-cap-so.js')
// .js('resources/js/bao-cao-cho-bo.js', 'public/js/bao-cao-cho-bo.js')
// .js('resources/js/bao-cao-cho-so.js', 'public/js/bao-cao-cho-so.js')
// .js('resources/js/tinh-hinh-nop-du-lieu-cua-so.js', 'public/js/tinh-hinh-nop-du-lieu-cua-so.js')
// .js('resources/js/bao-cao-emis.js', 'public/js/bao-cao-emis.js')
// .js('resources/js/bao-cao-eqms.js', 'public/js/bao-cao-eqms.js')
// .js('resources/js/bao-cao-cua-don-vi.js', 'public/js/bao-cao-cua-don-vi.js')
// .js('resources/js/bao-cao-quan-ly-tieu-chi.js', 'public/js/bao-cao-quan-ly-tieu-chi.js')
// .js('resources/js/bao-cao-cho-truong.js', 'public/js/bao-cao-cho-truong.js')
// .js('resources/js/bao-cao-gui-len.js', 'public/js/bao-cao-gui-len.js')
// .js('resources/js/quan-ly-nguoi-dung.js', 'public/js/quan-ly-nguoi-dung.js')
// .js('resources/js/quan-ly-vai-tro.js', 'public/js/quan-ly-vai-tro.js')
// .js('resources/js/cau-hinh-email.js', 'public/js/cau-hinh-email.js')
// .js('resources/js/cau-hinh-mau-email.js', 'public/js/cau-hinh-mau-email.js')
// .js('resources/js/cau-hinh-lich-dong-bo.js', 'public/js/cau-hinh-lich-dong-bo.js')
// .js('resources/js/tra-cuu-yeu-cau-dong-bo-du-lieu.js', 'public/js/tra-cuu-yeu-cau-dong-bo.js')
// .js('resources/js/yeu-cau-dong-bo-du-lieu-cu.js', 'public/js/yeu-cau-dong-bo-du-lieu-cu.js')
// .js('resources/js/yeu-cau-dong-bo-du-lieu-theo-truong.js', 'public/js/yeu-cau-dong-bo-du-lieu-theo-truong.js')
// .js('resources/js/yeu-cau-dong-bo-du-lieu-theo-truong-ioc.js', 'public/js/yeu-cau-dong-bo-du-lieu-theo-truong-ioc.js')
// .js('resources/js/import-file-du-lieu-moet.js', 'public/js/import-file-du-lieu-moet.js')
// .js('resources/js/hoc-sinh-giao-vien-chuyen-truong.js', 'public/js/hoc-sinh-giao-vien-chuyen-truong.js')
// .js('resources/js/yeu-cau-nop-du-lieu-theo-bieu-mau.js', 'public/js/yeu-cau-nop-du-lieu-theo-bieu-mau.js')
// .js('resources/js/tieu-chi-du-lieu.js', 'public/js/tieu-chi-du-lieu.js')
// .js('resources/js/yeu-cau-nhap-lieu.js', 'public/js/yeu-cau-nhap-lieu.js')
// .js('resources/js/xem-du-lieu-dac-thu.js', 'public/js/xem-du-lieu-dac-thu.js')
// .js('resources/js/lich-su-day-du-lieu.js', 'public/js/lich-su-day-du-lieu.js')
// .js('resources/js/bao-cao-day-du-lieu.js', 'public/js/bao-cao-day-du-lieu.js')
.js('resources/js/tra-cuu-hoc-sinh.js', 'public/js/tra-cuu-hoc-sinh.js')
.js('resources/js/tra-cuu-ket-qua-hoc-tap.js', 'public/js/tra-cuu-ket-qua-hoc-tap.js')
.js('resources/js/tra-cuu-can-bo.js', 'public/js/tra-cuu-can-bo.js')
// .js('resources/js/sao-luu-du-lieu.js', 'public/js/sao-luu-du-lieu.js')
.js('resources/js/tra-cuu-lop-hoc.js', 'public/js/tra-cuu-lop-hoc.js')
// .js('resources/js/cau-hinh-duyet-day-du-lieu.js', 'public/js/cau-hinh-duyet-day-du-lieu.js')
// .js('resources/js/cau-hinh-duyet-day-du-lieu-ioc.js', 'public/js/cau-hinh-duyet-day-du-lieu-ioc.js')
// .js('resources/js/tra-cuu-can-bo-phong-so.js', 'public/js/tra-cuu-can-bo-phong-so.js')
// .js('resources/js/tra-cuu-hoc-sinh-dong-bo.js', 'public/js/tra-cuu-hoc-sinh-dong-bo.js')
// .js('resources/js/lich-su-chuyen-du-lieu.js', 'public/js/lich-su-chuyen-du-lieu.js')
// .js('resources/js/lich-su-day-du-lieu-len-bo.js', 'public/js/lich-su-day-du-lieu-len-bo.js')
// .js('resources/js/lich-su-day-du-lieu-len-ioc.js', 'public/js/lich-su-day-du-lieu-len-ioc.js')
// .js('resources/js/cau-hinh-duong-dan-logo.js', 'public/js/cau-hinh-duong-dan-logo.js')
// //
// //
// .js('resources/js/cap-nhat-doi-tac.js', 'public/js/cap-nhat-doi-tac.js')
// .js('resources/js/danh-sach-yeu-cau-du-lieu.js', 'public/js/danh-sach-yeu-cau-du-lieu.js')
// .js('resources/js/dashboard.js', 'public/js/dashboard.js')
// .js('resources/js/dashboard-school.js', 'public/js/dashboard-school.js')
// .js('resources/js/ket-chuyen-du-lieu.js', 'public/js/ket-chuyen-du-lieu.js')
// .js('resources/js/mat-khau-ket-chuyen.js', 'public/js/mat-khau-ket-chuyen.js')
// .js('resources/js/don-vi.js', 'public/js/don-vi.js')
// .js('resources/js/bao-cao-nhom-tieu-chi.js', 'public/js/bao-cao-nhom-tieu-chi.js')
// .js('resources/js/dm-truong-hoc.js', 'public/js/dm-truong-hoc.js')
//  .js('resources/js/dm-dan-toc.js', 'public/js/dm-dan-toc.js')
// .js('resources/js/dm-ton-giao.js', 'public/js/dm-ton-giao.js')
// .js('resources/js/dm-tinh-thanh.js', 'public/js/dm-tinh-thanh.js')
.js('resources/js/dm-quan-huyen.js', 'public/js/dm-quan-huyen.js')
// .js('resources/js/dm-phuong-xa.js', 'public/js/dm-phuong-xa.js')
// .js('resources/js/dm-to-thon.js', 'public/js/dm-to-thon.js')
// .js('resources/js/dm-chuyen-nganh-dao-tao.js', 'public/js/dm-chuyen-nganh-dao-tao.js')
// .js('resources/js/dm-mon-hoc.js', 'public/js/dm-mon-hoc.js')
// .js('resources/js/dm-loai-doi-tuong.js', 'public/js/dm-loai-doi-tuong.js')
// .js('resources/js/dm-linh-vuc-danh-gia-phat-trien.js', 'public/js/dm-linh-vuc-danh-gia-phat-trien.js')
// .js('resources/js/dm-chi-so-danh-gia-phat-trien.js', 'public/js/dm-chi-so-danh-gia-phat-trien.js')
// .js('resources/js/dm-chuan-chieu-cao-can-nang.js', 'public/js/dm-chuan-chieu-cao-can-nang.js')
// .js('resources/js/dm-doi-tuong-chinh-sach.js', 'public/js/dm-doi-tuong-chinh-sach.js')
// .js('resources/js/dm-ly-do-bo-hoc.js', 'public/js/dm-ly-do-bo-hoc.js')
// .js('resources/js/dm-quan-ly-doi-tac.js', 'public/js/dm-quan-ly-doi-tac.js')
// .js('resources/js/nop-du-lieu-sso.js', 'public/js/nop-du-lieu-sso.js')
// .js('resources/js/danh-muc-service-bo.js', 'public/js/danh-muc-service-bo.js')
// .js('resources/js/cap-nhat-doi-tac-truong.js', 'public/js/cap-nhat-doi-tac-truong.js')
// .js('resources/js/doi-mat-khau', 'public/js/doi-mat-khau.js')
// .js('resources/js/huong-dan-faq', 'public/js/huong-dan-faq.js')
// .js('resources/js/bao-cao-cho-so-v2.js', 'public/js/bao-cao-cho-so-v2.js')
// .js('resources/js/gui-yeu-cau-dong-bo-du-lieu', 'public/js/gui-yeu-cau-dong-bo-du-lieu.js')
// .js('resources/js/bao-cao-tinh-hinh-nop-du-lieu', 'public/js/bao-cao-tinh-hinh-nop-du-lieu.js')
// .js('resources/js/bao-cao-tinh-hinh-nop-du-lieu-theo-don-vi', 'public/js/bao-cao-tinh-hinh-nop-du-lieu-theo-don-vi.js')
// .js('resources/js/so-sanh-du-lieu-moet', 'public/js/so-sanh-du-lieu-moet.js')
// .js('resources/js/bao-cao-dong', 'public/js/bao-cao-dong.js')
// .js('resources/js/bao-cao-dong-emis', 'public/js/bao-cao-dong-emis.js')
// .js('resources/js/bao-cao-tieu-chi', 'public/js/bao-cao-tieu-chi.js')
// .js('resources/js/quan-ly-bao-cao', 'public/js/quan-ly-bao-cao.js')
// .js('resources/js/cau-hoi-thuong-gap', 'public/js/cau-hoi-thuong-gap.js')
// .js('resources/js/danh-sach-tieu-chi-trong-chinh-sua-template', 'public/js/danh-sach-tieu-chi-trong-chinh-sua-template.js')
// .js('resources/js/nop-du-lieu', 'public/js/nop-du-lieu.js')
// .js('resources/js/tong-hop-du-lieu.js', 'public/js/tong-hop-du-lieu.js')
// .js('resources/js/tong-hop-du-lieu-emis.js', 'public/js/tong-hop-du-lieu-emis.js')
// .js('resources/js/nhap-lieu-tieu-chi-ngoai', 'public/js/nhap-lieu-tieu-chi-ngoai.js')
// .js('resources/js/chinh-sua-template-bao-cao', 'public/js/chinh-sua-template-bao-cao.js')
// .js('resources/js/thong-tin-y-te-hoc-sinh', 'public/js/thong-tin-y-te-hoc-sinh.js')
// .js('resources/js/trang-chu-ioc-ban-do', 'public/js/trang-chu-ioc-ban-do.js')
// .js('resources/js/bao-cao-tich-hop', 'public/js/bao-cao-tich-hop.js')
// .js('resources/js/import-kiem-dinh-chat-luong', 'public/js/import-kiem-dinh-chat-luong.js')
// .js('resources/js/sap-nhap-truong', 'public/js/sap-nhap-truong.js')
// .js('resources/js/giai-the-truong', 'public/js/giai-the-truong.js')
// .js('resources/js/goi-cuoc-giao-vien', 'public/js/goi-cuoc-giao-vien.js')
// .js('resources/js/nhap-lieu-du-lieu-nam-hoc.js', 'public/js/nhap-lieu-du-lieu-nam-hoc.js')
// .js('resources/js/mat-khau-ket-chuyen-ioc.js', 'public/js/mat-khau-ket-chuyen-ioc.js')
// .js('resources/js/dong-bo-danh-muc.js', 'public/js/dong-bo-danh-muc.js')
//
// .npsass('resources/sass/app.scss', 'public/css');
// mix.autoload({
// 'jquery': ['$', 'window.jQuery', 'jQuery'],
// 'vue': ['Vue', 'window.Vue'],
// 'moment': ['moment', 'window.moment'],
// });
